# Generated by Django 4.1.10 on 2023-11-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whether',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Precitipation', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(null=True)),
                ('Month', models.IntegerField(null=True)),
                ('Week', models.IntegerField(null=True)),
                ('Year', models.DateTimeField(null=True)),
                ('Citys', models.CharField(blank=True, max_length=200)),
                ('Code', models.CharField(blank=True, max_length=200)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('AvgTemp', models.CharField(max_length=100, null=True)),
                ('MaxTemp', models.CharField(max_length=100, null=True)),
                ('MinTemp', models.CharField(max_length=100, null=True)),
                ('Speed', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
