# Generated by Django 4.1.10 on 2023-11-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_precitipation_whether_precipitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whether',
            name='Date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whether',
            name='Year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
